### PR TITLE
Kaghim's branch

### PR DESCRIPTION
**Pull request by abdelkrimnachef**
solve those ones : 
- improve BNN results : improve the architecture.
- improve training loop : refactor + use tqdm
- Varitional Inference : implement variational inference for BNNs. 
- plot epistmic uncertainty : BNNs like GPs allow us to quantify uncertainty.

### CODE REVIEW

**Comment by 1hachem** [comment]
great job you did here !
please, the way you are plotting epistimc uncertainty seems wrong, try using `plt.fill_between`

**Comment by abdelkrimnachef** [comment]
> great job you did here ! please, the way you are plotting epistimic uncertainty seems wrong, try using `plt.fill_between`
> 
> plot a 3σ confidence interval

check the last commit if thats wrong let me know

**Comment by 1hachem** [comment]
try using `plt.fill_between` to plot the uncertainty and have a smooth coloring just like this figure 
image

**Comment by 1hachem** [comment]
Going to close this pull request since it has not been active for a while, however we like your contribution and we would like to further chat with you, @Scheraft will contact you for further details ! 🇩🇿 🚀

**Pull request closed without merging**
