### PR TITLE
Mazzi nadjib v3

### PR DESCRIPTION
**Pull request by NadjibMazzi**
the final version of the project

### CODE REVIEW

**Comment by 1hachem** [comment]
please remove `.idea` directory

**Comment by 1hachem** [comment]
ignore `__pycache__` dirs

**Comment by 1hachem** [comment]
keep pushing new commits to this pull request dont creat a new one !

**Review by 1hachem — APPROVED** [review]
great work ! these can be accepted to merge

**Comment by 1hachem** [comment]
@NadjibMazzi well done ! you will be contacted soon to pass an interview for the position of AI engineer at BIGmama, meanwhile we welcome you to provide a feedback regarding the challange at hand, did you learn anything new ? is there a way for use to improve the hiring process ?

**Comment by NadjibMazzi** [comment]
Great news, thank you for your interest

**Pull request merged**
